[[redirects]]
  from = "/qqmap/*"
  to = "https://apis.map.qq.com/:splat"
  status = 200

[[redirects]]
  from = "/caiyun/*"
  to = "https://api.caiyunapp.com/v2.6/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
